### ISSUE TITLE
log-in email pw

### ISSUE THREAD

**Issue by hakan-b** [Charlie-Root/homey-nl-verisure#20]
Have a Verisure security system in Sweden.
Using the same email/pw that I use for the Mypages.verisure.com and the iPhone app is not working when  trying to login to the Verisure Homey app.
Is there an other email/pw to be used or is your Homey/verisure app not working for Swedish Verisure systems?

**Comment by Merlinuf** [comment]
Hi,

I live in sweden and it works for me


Med vänlig hälsning,

Kristoffer

**Comment by hakan-b** [comment]
Hi Kristoffer
Did you use the same login to the Homey app as for your smartphone and Mypages?
///Håkan

**Comment by hakan-b** [comment]
I understand that- but my question was the login to the Verisure homey app ( not to Homey control unit) to access my Verisure account (and its sensors)
///Håkan

Hämta Outlook för iOS<https://aka.ms/o0ukef>

________________________________
Från: Merlinuf <notifications@github.com>
Skickat: måndag, juli 16, 2018 8:24 fm
Till: Charlie-Root/homey-nl-verisure
Kopia: hakan-b; Author
Ämne: Re: [Charlie-Root/homey-nl-verisure] log-in email pw (#20)

Well homey is one login and Verisure another


Med vänlig hälsning,

Kristoffer

**Comment by Merlinuf** [comment]
Ok, yes same


Med vänlig hälsning,

Kristoffer

**Comment by hakan-b** [comment]
I have doubled checked using the same email/pw to the Verisure-Homey app as for login on to Versisure account on my iPhone-app as well as to Verisures Mypage without success. I am 100% sure that I use the same email and pw but it does not work on the Verisure/Homey app. I a have restarted the Homey without any effect.
Any suggestions to get this working - anyone experienced the same problem??

**Comment by jampeef** [comment]
Works fine here
________________________________

**Comment by nerdtechse** [comment]
Try to uninstall the app and then install it again. Worked for me..

**Comment by Charlie-Root** [comment]
Hi,

make sure the account has enough privileges (if the iphone app works, so will homey using the same credentials)

Wieger

**Comment by Chrissba** [comment]
I have the same issue, I get a “Invalid e-mail address or password” message the moment I click the log in button.

The Verisure username and password works with the “Yale Doorman” app. I’ve tried a reinstall without any luck, any suggestions? 

Chriss

**Comment by Charlie-Root** [comment]
Should be fixed in 1.0.9, pending approval at Athom

**Comment by Chrissba** [comment]
I have updated to 1.0.9, and reinstalled but I still get a “Invalid e-mail address or password” message the moment I click the log in button.

**Comment by Chrissba** [comment]
The console view shows these two errors when I click Log in:

(index):152 Ignored call to 'alert()'. The document is sandboxed, and the 'allow-modals' keyword is not set.
(anonymous) @ (index):152
---
Uncaught ReferenceError: addressEl is not defined
    at Function.<anonymous> ((index):172)
    at n.onMessage (homey.js:1)
