### ISSUE TITLE
Verisure Doorlock - Norway

### ISSUE THREAD

**Issue by prj84** [Charlie-Root/homey-nl-verisure#40]
After update to v.2.0 (and v.2.2) no Arm states is updated (or transfered to Verisure). Door lock does not respond to changes. Sensors can not be added (just spinning wheel), Smoke detectors can not be added (just spinning wheel).

Same thing is happening to my colleague  that has the same setup.

What can we try?

**Comment by Charlie-Root** [comment]
Please try completely de-installing the app and re-adding it. That should solve it. After installing the app, logon through settings and enter doorkey. Wait 30 seconds and add the alarm

**Comment by prj84** [comment]
I have tried this before and again now. Still do not work :-/

**Comment by prj84** [comment]
I tried to install the Yale Doorman - Verisure app for Homey just now. That works without any problems and get status instant.

**Comment by Charlie-Root** [comment]
So this is only the doorlock. 

I will check the code for that

**Comment by Charlie-Root** [comment]
Duplicate #39

**Comment by prj84** [comment]
After trying almost 30 times the app now update alarm status. A bit lag, but now works fine. It is not possible to set alarm state. It never changes. (The pin and everything is correct)
